export interface QaSkillManifest {
  apiVersion: 'qa-agent/v2';
  kind: 'Skill';
  metadata: { name: string; version: string; description: string; lifecycle: 'active' };
  requirements: { capabilities: { required: string[]; optional: string[] } };
  safety: { riskLevel: 'low' | 'medium'; writeAccess: false };
  outputs: { type: 'object'; properties: Record<string, unknown> };
}

export const builtInSkills: QaSkillManifest[] = [
  { apiVersion: 'qa-agent/v2', kind: 'Skill', metadata: { name: 'browser.interact', version: '2.0.0', description: 'Navigate, click, fill, and wait in a real browser within the safety policy.', lifecycle: 'active' }, requirements: { capabilities: { required: ['browser.interact'], optional: ['browser.inspect'] } }, safety: { riskLevel: 'medium', writeAccess: false }, outputs: { type: 'object', properties: { actions: { type: 'array' } } } },
  { apiVersion: 'qa-agent/v2', kind: 'Skill', metadata: { name: 'visual.verify', version: '2.0.0', description: 'Verify rendered business outcomes against screenshots and business rules.', lifecycle: 'active' }, requirements: { capabilities: { required: ['browser.inspect'], optional: ['vision.inspect'] } }, safety: { riskLevel: 'low', writeAccess: false }, outputs: { type: 'object', properties: { expected: { type: 'string' }, actual: { type: 'string' }, status: { type: 'string' } } } },
  { apiVersion: 'qa-agent/v2', kind: 'Skill', metadata: { name: 'evidence.capture', version: '2.0.0', description: 'Capture screenshots, page state, console output, network failures, and traces as test evidence.', lifecycle: 'active' }, requirements: { capabilities: { required: ['browser.inspect'], optional: ['network.read', 'logs.read'] } }, safety: { riskLevel: 'low', writeAccess: false }, outputs: { type: 'object', properties: { evidence: { type: 'array' } } } },
  { apiVersion: 'qa-agent/v2', kind: 'Skill', metadata: { name: 'operation.replay', version: '2.0.0', description: 'Execute an approved project-local OperationPlan in order after validating context, MCP health, and permissions.', lifecycle: 'active' }, requirements: { capabilities: { required: [], optional: ['browser.interact', 'android.adb', 'ios.simulator.interact'] } }, safety: { riskLevel: 'medium', writeAccess: false }, outputs: { type: 'object', properties: { replayStatus: { type: 'string' }, operationId: { type: 'string' }, adaptations: { type: 'array' } } } },
  { apiVersion: 'qa-agent/v2', kind: 'Skill', metadata: { name: 'report.generate', version: '2.0.0', description: 'Generate a Markdown QA report from the Run, assertions, and evidence.', lifecycle: 'active' }, requirements: { capabilities: { required: [], optional: [] } }, safety: { riskLevel: 'low', writeAccess: false }, outputs: { type: 'object', properties: { reportPath: { type: 'string' } } } },
  { apiVersion: 'qa-agent/v2', kind: 'Skill', metadata: { name: 'memory.curate', version: '2.0.0', description: 'Distill run outcomes into candidate project memory and update durable knowledge after review.', lifecycle: 'active' }, requirements: { capabilities: { required: [], optional: [] } }, safety: { riskLevel: 'low', writeAccess: false }, outputs: { type: 'object', properties: { candidateIds: { type: 'array' } } } },
  { apiVersion: 'qa-agent/v2', kind: 'Skill', metadata: { name: 'source.readonly', version: '2.0.0', description: 'Perform read-only source-assisted diagnosis after observing the real business outcome.', lifecycle: 'active' }, requirements: { capabilities: { required: ['source.readonly'], optional: [] } }, safety: { riskLevel: 'low', writeAccess: false }, outputs: { type: 'object', properties: { findings: { type: 'array' } } } },
];
