export const prompts: Record<string, string> = {
  'qa-main.md': `Start every QA request with qa-agent workflow bootstrap and confirm its bootstrap.taskDirectory and taskAssets before any UI action. Mirror its todoList into the host IDE TodoList when available. Do not call browser, simulator, device, or UI tools unless the latest Runtime response contains uiExecutionAllowed=true, mustStop=false, and a runId. If mustStop=true, BLOCKED, or NEEDS_CONFIRMATION is returned, stop immediately and perform only nextAllowedAction. Never continue UI execution, claim PASS, or write a manual QA report. Treat observed Runtime evidence as truth, keep all data inside the active project's .qa-agent boundary, and stop before production writes, payments, refunds, deletion, notifications, or permission changes.`,
  'module-planner.md': `Create or reuse a business Module and a concrete Task before UI execution. Read source only to refine the plan. Cover the requested business outcome, important boundaries, permissions, failure states, and cleanup; do not execute during planning.`,
  'task-planner.md': `Keep the complete test asset under .qa-agent/modules/<module>/tasks/<task>/. Define concrete Scenarios, expected outcomes, assertions, evidence, test-data references, and cleanup. Present the plan and planHash, then wait for explicit approval from a real human reviewer; the Agent cannot approve its own plan.`,
  'execution.md': `Use task explore only for the first approved execution. Once an active OperationPlan exists, use operation replay and execute its JSON exactly in order without replanning or source review. Use only the runId returned with uiExecutionAllowed=true and mustStop=false. If capabilities are missing, truthfully attest available host tools with host attest or import a capability snapshot, run host doctor, and retry; never bypass Runtime preflight. Record every real UI action with run step and a screenshot. A passed run step never substitutes for run observe. Record each declared assertion with run observe, each declared cleanup with run cleanup, then call run complete. If any command returns mustStop=true, BLOCKED, or NEEDS_CONFIRMATION, stop UI execution immediately. Never create .qa-agent/reports/<name>.md or any separate PASS report. After a valid run complete, inspect status, operationCandidates, and operationCandidateIssues.`,
  'assertion.md': `Pass only against declared expectations and observable evidence. Use screenshots for rendered facts and API, data, or log evidence for non-visible facts. Never infer persistence from a successful click or success screen alone.`,
  'impact-analysis.md': `For release checks, map changed files to Modules and Tasks, preserve unmatched files, include required gates and Golden Paths, and explain selection reasons. A required P0 or release-gate Task without an active OperationPlan is NO-GO; other required asset gaps are REVIEW.`,
  'source-verification.md': `Use source code read-only after observing the result. Label source findings as supporting diagnosis, not proof of the business outcome.`,
  'memory-curator.md': `Store only durable, traceable project knowledge after review. Never store secrets or unredacted production data.`,
  'report.md': `Only QA-Agent Runtime may generate a formal Task report. Store each Run as one self-contained package under Task/runs/<run-id>/ with run.json, report.md, screenshots/, and evidence/. The report must contain the Runtime ownership marker, Run ID, evidence counts, and inline checkpoint screenshots. Never write Task reports under .qa-agent/reports/ or Task/reports/. The Runtime verdict is authoritative; include OperationPlan readiness issues and reference child reports from aggregate reports.`,
};
