import { readProject, taskSourceRunReportPath } from './project.ts';
import { runtimeReportMarker } from './report-contract.ts';
import { writeTextAtomic } from './store.ts';
import type { TestRun, TestTask } from './types.ts';

export function writeReport(root: string, task: TestTask, run: TestRun): string {
  const screenshotBacked = run.screenshots.length > 0;
  const project = readProject(root);
  const relativeAsset = (path: string): string => path.startsWith('source-run/') ? path.slice('source-run/'.length) : path;
  const image = (path: string, alt: string): string => `![${alt}](./${relativeAsset(path)})`;
  const visualFailures = run.visualFindings.filter(item => item.status === 'failed');
  const scenarioFailures = run.scenarioResults.filter(item => item.status === 'failed');
  const defectCandidates = [
    ...visualFailures.map(item => ({ id: `visual-${item.scenarioId}-${item.assertionId}`, scenario: item.scenarioId, expected: item.expected, actual: item.actual, screenshot: item.screenshotPath })),
    ...scenarioFailures.filter(item => !visualFailures.some(finding => finding.scenarioId === item.scenarioId)).map(item => ({ id: `execution-${item.scenarioId}`, scenario: item.scenarioId, expected: 'Declared scenario expectations', actual: item.detail ?? 'Scenario failed without additional detail.', screenshot: undefined as string | undefined })),
  ];
  const checkpoints = task.scenarios.filter(scenario => !run.scenarioId || scenario.id === run.scenarioId).flatMap(scenario => (scenario.visualAssertions ?? []).map(assertion => ({ scenarioId: scenario.id, id: assertion.id, description: assertion.expected })));
  const checkpointLines = checkpoints.flatMap(checkpoint => {
    const finding = run.visualFindings.find(item => item.scenarioId === checkpoint.scenarioId && item.assertionId === checkpoint.id);
    if (!finding) return [`### ${checkpoint.id}`, '', `- Scenario: ${checkpoint.scenarioId}`, `- Expected: ${checkpoint.description}`, '- Status: MISSING', '- Screenshot: missing', ''];
    return [`### ${checkpoint.id}`, '', `- Scenario: ${checkpoint.scenarioId}`, `- Status: ${finding.status.toUpperCase()}`, `- Expected: ${finding.expected}`, `- Actual: ${finding.actual}`, `- Screenshot: ${finding.screenshotPath ?? 'missing'}`, ...(finding.screenshotPath ? [image(finding.screenshotPath, `Checkpoint ${checkpoint.id}`)] : []), ''];
  });
  const eligibility = run.pythonRegressionEligibility;
  const lines = [
    runtimeReportMarker(run.id),
    ...(screenshotBacked ? [] : ['<!-- QA-AGENT:SOURCE-RUN-DIAGNOSTIC -->']),
    screenshotBacked ? `# QA Run: ${task.metadata.name}` : `# QA Run Diagnostic: ${task.metadata.name}`, '',
    screenshotBacked
      ? '> Generated by QA-Agent Runtime from the persisted Run. Manually written summaries are not authoritative.'
      : '> Diagnostic only. No formal test report can be produced because no real screenshot was captured.', '',
    '## Runtime Assets', '',
    `- Run ID: ${run.id}`,
    `- Runtime generator: ${run.reportGeneratedBy ?? 'missing'}`,
    `- Generated at: ${run.reportGeneratedAt ?? 'unknown'}`,
    `- Report path: ${run.reportPath ?? 'source-run/report.md'}`,
    `- Screenshot count: ${run.screenshots.length}`,
    `- Evidence count: ${run.evidence.length}`, '',
    '## Test Context', '',
    `- Project: ${project.project.name}`,
    `- Module: ${run.moduleId}`,
    `- Task: ${run.taskId}`,
    `- Module snapshot: ${task.moduleSnapshot?.snapshotHash ?? 'not materialized'} (revision ${task.moduleSnapshot?.moduleRevision ?? 'unknown'})`,
    `- Environment: ${run.context.environment}`,
    `- Platform: ${run.context.platform}`,
    `- Role: ${run.context.role}`,
    `- Scenario: ${run.scenarioId ?? 'all selected scenarios'}`,
    `- Device: ${run.context.device ?? 'unknown'}`,
    `- App version: ${run.context.appVersion ?? 'unknown'}`,
    `- Web build: ${run.context.webBuild ?? 'unknown'}`,
    `- Git Branch: ${run.git.branch ?? 'unknown'}`,
    `- Git Commit: ${run.git.commit ?? 'unknown'}`,
    `- Safe Mode: ${run.safeMode}`,
    `- Plan hash: ${run.planHash ?? 'unknown'}`,
    `- MCP snapshot: ${run.context.mcpSnapshot.map(item => `${item.id}:${item.status}/${item.permissionStatus}`).join(', ') || 'none'}`,
    `- Permission snapshot: ${run.context.permissionSnapshot.status}`, '',
    '## Business Scope', '',
    `- Description: ${task.description}`,
    ...task.objectives.map(item => `- Business objective: ${item}`),
    ...task.scenarios.map(scenario => `- ${scenario.id}: ${scenario.title}\n  - Intent: ${scenario.intent}\n  - Expected: ${JSON.stringify(scenario.expected)}\n  - Evidence: ${scenario.evidence.join(', ')}`), '',
    '## Conclusion', '', run.status.toUpperCase(), '',
    '## Scenario Results', '',
    ...run.scenarioResults.map(item => `- ${item.scenarioId}: ${item.status.toUpperCase()}${item.detail ? ` — ${item.detail}` : ''}`), '',
    '## Execution Steps', '',
    ...run.steps.map(step => `- ${step.action}: ${step.status.toUpperCase()} — ${step.detail}${step.uiAction ? `\n  - Action type: ${step.uiAction}` : ''}${step.executionMode ? `\n  - Execution mode: ${step.executionMode}` : ''}${step.locator ? `\n  - Planned locator: ${step.locator.strategy}${step.locator.value ? `=${step.locator.value}` : ''}` : ''}${step.actualLocator ? `\n  - Actual locator: ${step.actualLocator.strategy}${step.actualLocator.value ? `=${step.actualLocator.value}` : ''}` : ''}${step.expectedState ? `\n  - Expected state: ${step.expectedState}` : ''}${step.actualState ? `\n  - Actual state: ${step.actualState}` : ''}${step.adaptation ? `\n  - Adaptation: ${step.adaptation}` : ''}${step.guidedApprovalId ? `\n  - Guided approval: ${step.guidedApprovalId}` : ''}${step.humanVerdict ? `\n  - QA verdict: ${step.humanVerdict.status.toUpperCase()} by ${step.humanVerdict.confirmedBy}${step.humanVerdict.note ? ` — ${step.humanVerdict.note}` : ''}` : ''}${step.screenshotPath ? `\n  - Screenshot: ${step.screenshotPath}` : ''}`), '',
    ...(run.guidedInteraction ? ['## Guided QA Decisions', '', ...run.guidedInteraction.actionApprovals.map(item => `- ${item.id}: APPROVED by ${item.confirmedBy}\n  - Action: ${item.action}\n  - Expected: ${item.expected}\n  - QA reply: ${item.statement}`), ...run.guidedInteraction.verdicts.map(item => `- ${item.stepId}: ${item.status.toUpperCase()} by ${item.confirmedBy}\n  - QA reply: ${item.statement}${item.note ? `\n  - Note: ${item.note}` : ''}`), ''] : []),
    '## Evidence', '',
    ...run.evidence.flatMap(item => [`- ${item.type}: ${item.summary}${item.path ? ` (${item.path})` : ''}`, ...(item.type === 'screenshot' && item.path ? [image(item.path, item.summary)] : [])]), '',
    '## Embedded Screenshots', '',
    ...(run.screenshots.length ? run.screenshots.flatMap((screenshot, index) => [
      `### Screenshot ${index + 1}`,
      '',
      `- Step: ${screenshot.stepId}`,
      `- Captured at: ${screenshot.capturedAt}`,
      `- Visual inspection: ${screenshot.visualInspection}`,
      `- Summary: ${screenshot.summary}`,
      `- Source: ${screenshot.path}`,
      image(screenshot.path, screenshot.summary || `Screenshot ${index + 1}`),
      '',
    ]) : ['No screenshots were captured. This file is diagnostic only and is not a formal test report.', '']),
    '## Critical Checkpoints', '', ...(checkpointLines.length ? checkpointLines : ['- No checkpoint was declared.', '']),
    '## Visual Assertions', '',
    ...run.visualFindings.flatMap(item => [`- ${item.scenarioId}/${item.assertionId}: ${item.status.toUpperCase()}\n  - Expected: ${item.expected}\n  - Actual: ${item.actual}${item.screenshotPath ? `\n  - Screenshot: ${item.screenshotPath}` : ''}`, ...(item.screenshotPath ? [image(item.screenshotPath, `${item.scenarioId} ${item.assertionId}`)] : [])]), '',
    '## Cleanup', '', ...(run.cleanupFindings.length ? run.cleanupFindings.map(item => `- ${item.scenarioId}: ${item.cleanup} — ${item.status.toUpperCase()}\n  - Actual: ${item.actual}${item.screenshotPath ? `\n  - Screenshot: ${item.screenshotPath}` : ''}`) : ['- No declared cleanup result recorded.']), '',
    '## Python Regression Eligibility', '',
    `- Eligible: ${eligibility?.eligible ? 'yes' : 'no'}`,
    ...(eligibility?.eligible ? [`- Source flow hash: ${eligibility.flowHash}`, `- Source steps: ${eligibility.sourceStepIds.join(', ')}`, `- Scenarios: ${eligibility.scenarioIds.join(', ')}`] : eligibility?.issues.flatMap(item => [`- ${item.scenarioId}`, ...item.reasons.map(reason => `  - ${reason}`)]) ?? ['- Eligibility was not evaluated.']), '',
    '## Defect Candidates', '',
    ...(defectCandidates.length ? defectCandidates.flatMap(item => [`- ${item.id}`, `  - Scenario: ${item.scenario}`, `  - Expected: ${item.expected}`, `  - Actual: ${item.actual}`, ...(item.screenshot ? [`  - Screenshot: ${item.screenshot}`] : [])]) : ['- No failure evidence was classified.']), '',
    '## Recovery', '', ...(run.recoveryAttempts.length ? run.recoveryAttempts.map(item => `- ${item.id}: ${item.reason}\n  - Action: ${item.action}\n  - Outcome: ${item.outcome}\n  - Detail: ${item.detail}`) : ['- No recovery attempt recorded.']), '',
    ...(run.memoryCandidates?.length ? ['## Candidate Project Memory', '', ...run.memoryCandidates.map(item => `- ${item}`), ''] : []),
  ];
  const path = taskSourceRunReportPath(root, task.metadata.moduleId, task.metadata.id);
  writeTextAtomic(path, `${lines.join('\n')}\n`);
  return path;
}
