export const schemas: Record<string, object> = {
  'project.schema.json': { $schema: 'https://json-schema.org/draft/2020-12/schema', type: 'object', required: ['version', 'project', 'platforms', 'defaultContext', 'source', 'storage'] },
  'module.schema.json': { $schema: 'https://json-schema.org/draft/2020-12/schema', type: 'object', required: ['version', 'revision', 'id', 'name', 'status', 'riskLevel', 'platforms', 'roles'] },
  'task.schema.json': { $schema: 'https://json-schema.org/draft/2020-12/schema', type: 'object', required: ['apiVersion', 'kind', 'metadata', 'moduleSnapshotRef', 'requirementsRef', 'testPlanRef', 'scenarioRefs', 'regressionSuiteRef', 'reportIndexRef', 'runRefs', 'capabilities', 'safety', 'evidence', 'evidencePolicy', 'operationPlanRefs', 'recoveryPolicy'] },
  'run.schema.json': { $schema: 'https://json-schema.org/draft/2020-12/schema', type: 'object', required: ['id', 'taskId', 'moduleId', 'context', 'status', 'steps', 'startedAt'] },
  'memory.schema.json': { $schema: 'https://json-schema.org/draft/2020-12/schema', type: 'object', required: ['id', 'type', 'title', 'content', 'knowledgeLevel', 'confidence', 'source'] },
  'policy.schema.json': { $schema: 'https://json-schema.org/draft/2020-12/schema', type: 'object', required: ['safeMode', 'prohibitedActions', 'stopBefore'] },
  'mcp.schema.json': { $schema: 'https://json-schema.org/draft/2020-12/schema', type: 'object', required: ['version', 'connections'] },
  'skill.schema.json': { $schema: 'https://json-schema.org/draft/2020-12/schema', type: 'object', required: ['apiVersion', 'kind', 'metadata'] },
  'operation.schema.json': { $schema: 'https://json-schema.org/draft/2020-12/schema', type: 'object', required: ['apiVersion', 'kind', 'id', 'version', 'status', 'taskId', 'moduleId', 'scenarioId', 'planHash', 'executionSnapshot', 'steps'] },
  'module-snapshot.schema.json': { $schema: 'https://json-schema.org/draft/2020-12/schema', type: 'object', required: ['apiVersion', 'kind', 'moduleId', 'moduleName', 'moduleRevision', 'snapshotHash', 'capturedAt'] },
  'requirements.schema.json': { $schema: 'https://json-schema.org/draft/2020-12/schema', type: 'object', required: ['apiVersion', 'kind', 'taskId', 'moduleId', 'businessGoals', 'actors', 'flows', 'rules', 'scope', 'preconditions', 'testDataRefs', 'environments'] },
  'test-plan.schema.json': { $schema: 'https://json-schema.org/draft/2020-12/schema', type: 'object', required: ['apiVersion', 'kind', 'taskId', 'moduleId', 'version', 'planHash', 'scenarioRefs', 'capabilities', 'safety', 'evidencePolicy', 'recoveryPolicy', 'status'] },
  'regression-suite.schema.json': { $schema: 'https://json-schema.org/draft/2020-12/schema', type: 'object', required: ['apiVersion', 'kind', 'id', 'version', 'scope', 'moduleId', 'members', 'selectionPolicy', 'failurePolicy', 'contextPolicy', 'suiteHash', 'status'] },
  'regression-run.schema.json': { $schema: 'https://json-schema.org/draft/2020-12/schema', type: 'object', required: ['apiVersion', 'kind', 'id', 'suiteId', 'suiteVersion', 'suiteHash', 'moduleId', 'context', 'status', 'childRuns', 'startedAt'] },
};
